config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"

  resources :posts do
    resources :comments
  end

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment__content">
    <p class="comment__name"><strong><%= comment.name %></strong></p>
    <p class="comment__body"><%= comment.body %></p>
    <p class="comment__time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <% if user_signed_in? %>
    <%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn--right" %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="sidebar">
    <%= link_to root_path do %>
      <%= image_tag "profile.jpg", class: "logo" %>
    <% end %>

    <nav class="nav">
      <p class="nav__title">Website</p>
      <%= link_to "Blog", root_path, class: "nav__item" %>
      <%= link_to "About", about_path, class: "nav__item" %>
    </nav>

    <ul class="nav">
      <p class="nav__title">Social</p>
      <a class="nav__item" href="http://twitter.com/rubenmoya_">Twitter</a>
      <a class="nav__item" href="http://facebook.com/rubenmoya.web">Facebook</a>
      <a class="nav__item" href="http://github.com/rubenmoya">Github</a>
    </ul>

    <% if !user_signed_in? %>
      <%= link_to "Admin Login", new_user_session_path, class: "sign_in" %>
    <% end %>
  </div>
  <main class="main_content">
    <div class="header">
      <% if current_page?(root_path) %>
        <p class="header__title">All posts</p>
      <% elsif current_page?(about_path) %>
        <p class="header__title">About</p>
      <% else %>
        <%= link_to "Back to home", root_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="header__nav">
          <%= link_to "New Post", new_post_path, class: "btn--header" %>
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "btn--header" %>
        </div>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>


    <%= yield %>
  </main>

</body>
</html>

app/views/pages/about.html.erb
<div class="page">
  <%= image_tag "profile.jpg", class: "page__profile_image" %>

  <div class="page__content">
    <h1>Hey, I'm Rubén Moya</h1>
    <p>This is the week 2 of the <a href="http://twitter.com/mackenziechild">Mackenzie</a> 12 Weeks Challenge</p>
    <p>This week he built a blog in Rails 4.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit%><br>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="post">
  <h1>Edit post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post-list">
    <h2 class="post-list__title"><%= link_to post.title, post %></h2>
    <p class="post-list__date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="post">
  <% if @post.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New post</h1>

  <%= form_for :post, url: posts_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit%><br>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post">
  <h1 class="post__title">
    <%= @post.title %>
  </h1>
  <p class="post__date">
    Subbmite <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="post__body">
    <%= @post.body %>
  </div>

  <div class="comments">
    <h2 class="comment__title"><%= pluralize(@post.comments.count, 'comment') %></h2>
    <%= render @post.comments %>

    <h3 clas="comment__subtitle">Add a comment</h3>
    <%= render "comments/form" %>
  </div>
</div>